version: 2

project_name: lockify

# Build configuration
builds:
  - main: ./main.go
    binary: lockify
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/ahmed-abdelgawad92/lockify/cmd.Version={{ .Version }}
    env:
      - CGO_ENABLED=0

# Archive configuration (creates tar.gz/zip files)
archives:
  - formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    files:
      - README.md
      - LICENSE

# Checksums
checksum:
  name_template: 'checksums.txt'
  algorithm: sha256

# Changelog generation
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - Merge pull request
      - Merge branch

# Homebrew Cask (for pre-built binaries)
# Tap repository: https://github.com/ahmed-abdelgawad92/homebrew-lockify
# On release, goreleaser will create/update the Caskfile automatically
# Users can install with:
#   brew tap ahmed-abdelgawad92/lockify
#   brew install --cask lockify
# Or directly: brew install --cask ahmed-abdelgawad92/lockify
homebrew_casks:
  - name: lockify
    repository:
      owner: ahmed-abdelgawad92
      name: homebrew-lockify
    homepage: "https://github.com/ahmed-abdelgawad92/lockify"
    description: "Secure environment variable management"

# Snapshot builds (for testing)
snapshot:
  version_template: "{{ .Tag }}-next"

# Release notes template
release:
  mode: replace
  header: |
    ## Lockify {{ .Tag }}
    
    ### Installation
    
    **Option 1: Direct Download (All Platforms)**
    
    Download the binary for your platform from the assets below:
    - **Linux**: `lockify_linux_amd64.tar.gz` or `lockify_linux_arm64.tar.gz`
    - **macOS**: `lockify_darwin_amd64.tar.gz` or `lockify_darwin_arm64.tar.gz`
    - **Windows**: `lockify_windows_amd64.zip` or `lockify_windows_arm64.zip`
    
    Extract and add to your PATH.
    
    **Option 2: Package Managers (Optional)**
    
    - **macOS**: `brew install --cask ahmed-abdelgawad92/lockify/lockify`

